[deploy]
bucket = 'rm-cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdSyncRole'

[parameters]
GitHubOrg = 'DataCleansingEnthusiast'
RepositoryName = 'aws-bootcamp-cruddur-2023'
OIDCProviderArn = ''