[deploy]
bucket = 'rm-cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://roopish-awssolutions.com'
EnvBackendUrl = 'https://api.roopish-awssolutions.com'