[deploy]
bucket = 'rm-cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl= '*'
# EnvFrontendUrl = 'https://roopish-awssolutions.com'
EnvBackendUrl = '*'
# EnvBackendUrl = 'https://api.roopish-awssolutions.com'
DDBMessageTable = 'CrdDdb-DynamoDBTable-12ZX6Z3TOW6KN'