# Tables (or hash tables or dictionaries) are collections of key/value
# pairs. They appear in square brackets on a line by themselves.
# Empty tables are allowed and simply have no key/value pairs within them.
[deploy]
bucket = "rm-cfn-artifacts"
region = 'us-east-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:192212780887:certificate/27e48918-9c39-4bc8-8cd5-46f5a6603b19'
NetworkingStack = 'CrdNet'