[deploy]
bucket = 'rm-cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'DataCleansingEnthusiast/aws-bootcamp-cruddur-2023'
ArtifactBucketName = 'codepipeline-cruddur-artifacts-rm'
BuildSpec = 'backend-flask/buildspec.yml'