[deploy]
bucket = 'rm-cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdFrontend'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:192212780887:certificate/27e48918-9c39-4bc8-8cd5-46f5a6603b19'
WwwBucketName = 'www.roopish-awssolutions.com'
RootBucketName = 'roopish-awssolutions.com'